include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - curly_braces_in_flow_control_structures
    - unawaited_futures
    - prefer_final_locals
    - always_declare_return_types
